# Generated by Django 2.2.5 on 2020-01-23 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QnA',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('hit', models.IntegerField(null=True)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('writer_email', models.CharField(max_length=50)),
                ('img', models.BinaryField(null=True)),
                ('regdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
