# Generated by Django 2.2.5 on 2020-01-24 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='gdptable',
            managers=[
            ],
        ),
    ]
